### ISSUE TITLE
Error When Running Sovrin

### ISSUE THREAD

**Issue by howardkitto** [evernym/anoncreds#9]
I've managed to install Sovrin but when I run it I get the following error:

```
$ sovrin
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/sovrin", line 30, in <module>
    from sovrin.common.util import getConfig
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sovrin/__init__.py", line 4, in <module>
    from plenum.common.pkg_util import check_deps
ImportError: No module named 'plenum.common.pkg_util'
```

**Comment by dhh1128** [comment]
@howardkitto , what installation sequence are you using to install? I ask because this particular error has been seen before, and in other contexts it has been caused by having inconsistent dependencies due to an incomplete installation. You might try ```pip install --upgrade sovrin``` and see if it alters anything.

**Comment by howardkitto** [comment]
Yes that did it!

Thanks so much
